name: breez_translations
description: A new Flutter package project.
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: <2.4.0 # Requires Flutter 3.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  intl: ^0.18.1

dependency_overrides:
  intl: ^0.18.1

flutter:
  generate: true
